// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAC7vdEL8m0B5djLsWWcMTBA6Z2aPDEQ4',
    appId: '1:120825730847:web:d62ffaec061e844107c22a',
    messagingSenderId: '120825730847',
    projectId: 'ccapp-a04e3',
    authDomain: 'ccapp-a04e3.firebaseapp.com',
    storageBucket: 'ccapp-a04e3.appspot.com',
    measurementId: 'G-9VQGBCEHHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQk4Zosacxe6XR7JMH23P2i_EcPHVBQ2s',
    appId: '1:120825730847:android:eed51a34b90d04f707c22a',
    messagingSenderId: '120825730847',
    projectId: 'ccapp-a04e3',
    storageBucket: 'ccapp-a04e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrKmGHTA4y7Td9WkkHlwBO314ydamFvI',
    appId: '1:120825730847:ios:a9fd0bd15bcc67a407c22a',
    messagingSenderId: '120825730847',
    projectId: 'ccapp-a04e3',
    storageBucket: 'ccapp-a04e3.appspot.com',
    iosClientId: '120825730847-m5aitgpe5r7ttf2s987kbi99mucavj65.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccApp',
  );
}
