// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;


show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8lhURgj_gW6YuPWaEjXoOx39QCUN800',
    appId: '1:152916891359:web:fe36b5c1da02861fbcbb6a',
    messagingSenderId: '152916891359',
    projectId: 'ccapp-f875e',
    authDomain: 'ccapp-f875e.firebaseapp.com',
    storageBucket: 'ccapp-f875e.appspot.com',
    measurementId: 'G-B1NDD17JVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jRBJYg_2qWsdHuR3MbBOXdhjRBCQHEw',
    appId: '1:152916891359:android:5cb6972b717a2839bcbb6a',
    messagingSenderId: '152916891359',
    projectId: 'ccapp-f875e',
    storageBucket: 'ccapp-f875e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8liWoQi29bGI6NagcumJr5CH5KbvSZvw',
    appId: '1:152916891359:ios:7a30b4a89f23f59bbcbb6a',
    messagingSenderId: '152916891359',
    projectId: 'ccapp-f875e',
    storageBucket: 'ccapp-f875e.appspot.com',
    iosClientId:
        '152916891359-9jnilpjbk6l3ajbaq9eu8fqlaunk8q77.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccApp',
  );
}
